### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by BMannell** [VMorsaint/COSC3P97Project#1]
- [ ] touch detection for body parts
- [x] patient list
- [x] patient view
- [x] patient edit
- [x] patient create
- [x] file view
- [x] file edit
- [x] file create
- [ ] appointment view for today
- [ ] appointment view for patient
- [ ] appointment edit
- [ ] appointment create
- [ ] main view- should figure out what the main screen will display
